Implementation of the base project
Mih-Mir/MoneyManager pull request #1
Opened 2021-06-24 10:13 UTC by Mih-Mir

2021-06-28 07:03 UTC, sachenko-igor requested changes

2021-06-28 07:03 UTC, sachenko-igor commented on MoneyManager.ResourceAccess/Repositories/TransactionsRepository.cs
> +            _appDbContext.Transactions.RemoveRange(transactions);
is it working without SaveChanges?

2021-06-28 07:03 UTC, sachenko-igor commented on MoneyManager.ResourceAccess/Services/GetEnumValues.cs
> +        {
I don't like which folder you have choosen. This is not a service. All classes in Services folder must have "Services" postfix.  Refactor it. Create an Extensions folder and put this logic into an Extension method. 
create class EnumExtensions

2021-06-28 07:13 UTC, sachenko-igor requested changes

2021-06-28 07:13 UTC, sachenko-igor commented on MoneyManager.ResourceAccess/Repositories/TransactionsRepository.cs
> +            var result = _appDbContext.Transactions
I remember you have a misunderstanding here. Please implement another version of this method but without Group by Category. Use 2 separate queries and combine data on the backend side.
Just to be sure you understood this topic well and you are not having any issues here.

2021-06-28 07:13 UTC, sachenko-igor commented on MoneyManager.ResourceAccess/Repositories/TransactionsRepository.cs
> +                    g.Amount
This looks wrong. I don't believe that grouping by Amount is correct. If you have objections - let's discuss

2021-06-28 07:13 UTC, sachenko-igor commented on MoneyManager.ResourceAccess/Repositories/TransactionsRepository.cs
> +                .ToList()
If you materialize query and want to proceed with calculations on the backend side - ToList/FirstOrDefault/etc must be the last command. Create a variable for materialized data and work with this variable. It will make you code more readable and other developers will understand it better.

Refactory it for all the queries where you have materialized function.

2021-06-28 07:50 UTC, Mih-Mir commented on MoneyManager.ResourceAccess/Repositories/TransactionsRepository.cs
> +            _appDbContext.Transactions.RemoveRange(transactions);
Fixed

2021-06-28 08:20 UTC, Mih-Mir commented on MoneyManager.ResourceAccess/Services/GetEnumValues.cs
> +        {
Done.

2021-06-28 10:21 UTC, sachenko-igor requested changes

2021-06-28 10:21 UTC, sachenko-igor commented on MoneyManager.ResourceAccess/Repositories/TransactionsRepository.cs
> +                        var category = _appDbContext.Categories
get rid of DB call inside of the loop

2021-06-28 11:22 UTC, Mih-Mir commented on MoneyManager.ResourceAccess/Repositories/TransactionsRepository.cs
> +                        var category = _appDbContext.Categories
Fixed.

2021-06-28 11:22 UTC, Mih-Mir commented on MoneyManager.ResourceAccess/Repositories/TransactionsRepository.cs
> +                .ToList()
Fixed.

2021-06-28 11:22 UTC, Mih-Mir commented on MoneyManager.ResourceAccess/Repositories/TransactionsRepository.cs
> +                    g.Amount
Understood. Fixed.

2021-06-28 11:23 UTC, Mih-Mir commented on MoneyManager.ResourceAccess/Repositories/TransactionsRepository.cs
> +            var result = _appDbContext.Transactions
Done.

2021-06-28 11:23 UTC, Mih-Mir commented on MoneyManager.ResourceAccess/Repositories/TransactionsRepository.cs
> +        public void DeleteBuCurrentMonthTransactions(int userId)
Fixed.

2021-06-28 12:08 UTC, sachenko-igor requested changes

2021-06-28 12:08 UTC, sachenko-igor commented on MoneyManager.ResourceAccess/Repositories/TransactionsRepository.cs
> +                .Select(s => new
refactor it. group on SQL server side

2021-06-28 14:21 UTC, Mih-Mir commented on MoneyManager.ResourceAccess/Repositories/TransactionsRepository.cs
> +                .Select(s => new
Done

2021-06-28 14:26 UTC, Mih-Mir commented on MoneyManager.ResourceAccess/Repositories/TransactionsRepository.cs
> +            _appDbContext.Transactions.Add(model);
Not working. Sorry. Fixed.

2021-06-28 14:26 UTC, Mih-Mir commented on MoneyManager.ResourceAccess/Repositories/Interfaces/IAssetsRepository.cs
> +        void CreateAsset(Asset model);
Understood. Done.

2021-06-28 14:26 UTC, Mih-Mir commented on MoneyManager.ResourceAccess/Repositories/Interfaces/ICategoriesRepository.cs
> +        void CreateCategory(Category model);
Done.

2021-06-28 14:26 UTC, Mih-Mir commented on MoneyManager.ResourceAccess/Repositories/Interfaces/ITransactionsRepository.cs
> +        void CreateTransaction(Transaction model);
Done.

2021-06-28 14:26 UTC, Mih-Mir commented on MoneyManager.ResourceAccess/Repositories/Interfaces/IUsersRepository.cs
> +        void CreateUser(User model);
Done.

2021-06-29 07:09 UTC, sachenko-igor approved these changes

2021-06-29 07:30 UTC, merged